config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"
  resource :sessions, only: %i(destroy create new)
  resources :users
  resources :workers
  resource :worker_accounts, only: %i(show edit) do
    get :service_orders, on: :collection
  end
  resources :services do
    resources :service_orders, only: %i(new)
  end
  resources :service_orders, except: :new do
    get :cancellation_reason, on: :member
    get :rate, on: :member
  end
  resource :personal_informations, only: %i(show edit update)
  resources :notifications, only: %i(index destroy) do
    collection do
      delete :destroy_all
    end
  end
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :worker
  has_many :service_orders, dependent: :destroy
  has_many :categories, through: :worker

  validates :description, :title, presence: true
  validates :price, numericality: { bigger_than: 0 }

  after_update :notify_worker

  enum status: %i(on_review active not_active)

  def self.ransackable_attributes(auth_object = nil)
    ["city", "created_at", "description", "id", "price", "status", "title", "updated_at", "worker_id"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["categories", "service_orders", "worker"]
  end

  def notify_worker
    Notification.create(user_id: worker.user.id,
      work_account_notification: true,
      record_id: id,
      record_class: self.class.to_s,
      body: "Ваша послуга була розглянута! Переглянути результат") if saved_change_to_status? && (active? || not_active?)
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :worker_account_presence, :require_authorization, except: :show
  before_action :service, only: %i(show edit update destroy)

  def new
    @service = Service.new
  end

  def create
    @service = Service.create(service_params.merge(worker_id: current_user.worker.id))

    if @service.valid?
      redirect_to service_path(@service)
    else
      flash[:error] = @service.errors.full_messages
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    redirect_to root_path if current_user.worker.id != @service.worker.id

    if @service.update(service_params)
      redirect_to service_path(@service)
    else
      flash[:error] = @service.errors.full_messages
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    redirect_to root_path if current_user.worker.id != @service.worker.id

    @service.destroy
    redirect_to worker_accounts_path
  end

  private

  def service_params
    params.require(:service).permit(:title, :description, :price, :status)
  end

  def worker_account_presence
    redirect_to worker_accounts_path if current_user&.worker&.nil?
  end

  def service
    @service ||= Service.find_by(id: params[:id])
  end
end

app/helpers/services_helper.rb
module ServicesHelper
  def service_created_by_current_user?(worker_id)
    current_user.worker&.id == worker_id
  end

  def service_status(status)
    case status.to_sym
    when :on_review
      "На розгляді"
    when :active
      "Активний"
    when :not_active
      "Неактивний"
    end
  end
end

app/views/services/_service.html.erb
<%= link_to service_path(service), class: "service" do %>
  <div class="mb-3">
    <h4> <%= service.title %> </h4>
    <p> <%= service.description.truncate(50) %> </p>
    <p class="mt-4 text-xs"> <%= service.created_at.strftime("%F") %> </p>
  </div>
  <div class="flex items-center mt-auto">
    <div class="flex flex-col">
      <div> Ціна: </div>
      <b> <%= service.price %> </b>
    </div>
    <div class="button primary-button w-fit ml-auto"> Детально </div>
  </div>
<% end %>

app/views/services/_worker.html.erb
<div class="block-wrapper mt-5">
  <h2 class="mb-4"> Виконавець </h2>
  <p> <%= link_to @service.worker.full_name, worker_path(@service.worker), class: "font-medium text-xl text-blue-600" %> </p>
  <p class="mt-2"> Виконано замовлень: <%= @service.worker.service_orders.finished.count %> </p>
  <div class="flex">
    <p> Середня оцінка: </p>
    <p class="flex ml-1"> <%= star_icon %> <%= @service.worker.average_rate %> </p>
  </div>
  <p class="text-xs mt-2"> Зареєестрований на сайті <%= @service.worker.created_at.strftime("%F") %> </p>
</div>

app/views/services/edit.html.erb
<div class="w-2/3 mx-auto block-wrapper">
  <h2> Редагувати послугу </h2>
  <div class="text-red-600">
    <%= render template: "layouts/flash", locals: { flash: flash[:error] } %>
  </div>
  <%= form_with model: @service, method: :put, class: "flex flex-col" do |f| %>
    <%= f.hidden_field :status, {value: "on_review"} %>
    <div class="input-wrapper">
      <%= f.label :title, "Заголовок" %>
      <%= f.text_field :title, value: @service.title, required: true %>
    </div>
    <div class="input-wrapper">
      <%= f.label :description, "Опис" %>
      <%= f.text_area :description, value: @service.description, class: "min-h-[120px]", required: true %>
    </div>
    <div class="input-wrapper">
      <%= f.label :price, "Ціна" %>
      <%= f.text_field :price, value: @service.price, default: true, class: "mr-auto" %>
    </div>
    <div class="flex gap-4 mt-5 justify-end">
      <%= link_to "< Назад ", request.referrer, class: "button secondary-button" %>
      <%= f.submit "Підтвердити", class: "button primary-button" %>
    </div>
  <% end %>
</div>

app/views/services/new.html.erb
<div class="w-2/3 mx-auto block-wrapper">
  <h2> Створити нову послугу </h2>
  <div class="text-red-600">
    <%= render template: "layouts/flash", locals: { flash: flash[:error] } %>
  </div>
  <%= form_with model: @service, class: "flex flex-col" do |f| %>
    <div class="input-wrapper">
      <%= f.label :title, "Заголовок" %>
      <%= f.text_field :title, required: true %>
    </div>
    <div class="input-wrapper">
      <%= f.label :description, "Опис" %>
      <%= f.text_area :description, class: "min-h-[120px]", required: true %>
    </div>
    <div class="input-wrapper">
      <%= f.label :price, "Ціна" %>
      <%= f.text_field :price, default: true, class: "mr-auto" %>
    </div>
    <div class="flex gap-4 mt-5 justify-end">
      <%= link_to "< Назад ", request.referrer, class: "button secondary-button" %>
      <%= f.submit "Підтвердити", class: "button primary-button" %>
    </div>
  <% end %>
</div>

app/views/services/show.html.erb
<div class="block-wrapper">
  <%= link_to "< Назад ", request.referrer, class: "button secondary-button" %>
  <p class="text-xs mb-2 mt-4"> Опубліковано <%= time_ago_in_words(@service.created_at) %> </p>
  <h2> <%= @service.title %> </h2>
  <p class="text-2xl"> Ціна: <%= @service.price %> </p>
  <hr class="my-4">
  <h3> Опис </h3>
  <p> <%= @service.description %> </p>
  <div class="mt-4 flex gap-4">
    <% if current_user %>
      <% if service_created_by_current_user?(@service.worker_id) %>
        <%= link_to "Редагувати", edit_service_path(@service), class: "button primary-button" %>
        <% if @service.rejection_reason && @service.not_active? %>
          <div class='px-4 py-2 bg-red-200'>
            <h5> Причина відмови: </h5>
            <p><%= @service.rejection_reason %><p>
          </div>
        <% end %>
      <% end %>
      <% unless service_created_by_current_user?(@service.worker_id) %>
        <%= link_to "Замовити", new_service_service_order_path(@service), class: "button primary-button" %>
      <% end %>
    <% end %>
  </div>
</div>
<%= render partial: "services/worker" %>
<div class="block-wrapper mt-4">
  <h3> Останні оголошення автора </h3>
  <p class="text-gray-500 hover:text-gray-600"> <%= link_to "Всі оголошення автора >", worker_path(@service.worker) %> </p>
  <div class="service-wrapper pt-4">
    <% @service.worker.services.last(4).each do |service| %>
      <%= render partial: "services/service", locals: { service: service } %>
    <% end %>
  </div>
</div>