config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"
  resource :sessions, only: %i(destroy create new)
  resources :users
  resources :workers
  resource :worker_accounts, only: %i(show edit) do
    get :service_orders, on: :collection
  end
  resources :services do
    resources :service_orders, only: %i(new)
  end
  resources :service_orders, except: :new do
    get :cancellation_reason, on: :member
    get :rate, on: :member
  end
  resource :personal_informations, only: %i(show edit update)
  resources :notifications, only: %i(index destroy) do
    collection do
      delete :destroy_all
    end
  end
end

app/models/worker.rb
class Worker < ApplicationRecord
  belongs_to :user, optional: true
  has_many :services, dependent: :destroy
  has_many :service_orders, through: :services

  validates :description, presence: true

  has_many :worker_categories, dependent: :destroy
  has_many :categories, through: :worker_categories, dependent: :destroy

  delegate :full_name, to: :user

  def average_rate
    service_orders.average(:rate).to_f
  end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "description", "id", "looking_for_work", "updated_at", "user_id"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["categories", "service_orders", "services", "user", "worker_categories"]
  end

  private

  def categories_must_be_uniq
    errors.add(:base, "Категорії не повинні повторюватись") if categories.uniq.length != categories.length
  end
end

app/controllers/worker_accounts_controller.rb
class WorkerAccountsController < ApplicationController
  before_action :require_authorization, :worker_account_presence

  def show
    @worker_account = current_user.worker
    @pagy, @services = pagy(@worker_account.services)
  end

  def edit
    @worker = current_user.worker
  end

  def service_orders
    @worker_account = current_user.worker
    @pagy, @service_orders = pagy(@worker_account.service_orders.order(created_at: :desc))
  end

  private

  def worker_account_presence
    redirect_to worker_accounts_path if current_user&.worker&.nil?
  end
end

app/helpers/worker_accounts_helper.rb
module WorkerAccountsHelper
end

app/views/worker_accounts/_category.html.erb
<div class="px-2 py-1 bg-gray-200 rounded-md text-sm w-fit h-fit whitespace-nowrap"><%= category.title %> </div>

app/views/worker_accounts/_personal_info.html.erb
<div class="block-wrapper">
  <h2> Ваш робочий аккаунт </h2>
  <h4> Тут будуть відображені всі ваші послуги та замовлення, що зробили користувачі сайту. </h4>
  <hr>
  <h4 class="mt-4"> Ваша інформація </h4>
  <p>
    Категорія:
    <div class="flex gap-2 flex-wrap">
      <%= render partial: "worker_accounts/category", collection: @worker_account.categories, as: :category %>
    </div>
  </p>
  <p>
    Опис:
    <%= @worker_account.description %>
  </p>
  <%= render partial: "workers/opened_to_new_work", locals: { worker: @worker_account } %>
  <div class="flex gap-4 mt-5 justify-end">
    <%= link_to "Редагувати", edit_worker_accounts_path, class: "button primary-button" %>
    <%= link_to "Створити послугу", new_service_path, class: "button primary-button" %>
  </div>
</div>

app/views/worker_accounts/_service.html.erb
<div class="service">
  <%= link_to service_path(service) do %>
    <h3> <%= service.title %> </h3>
    <p> <%= service.description %> </p>
    <p> Статус: <%= service_status(service.status) %> </p>
  <% end %>
  <div class="mt-4 flex gap-3">
    <%= link_to "Редагувати", edit_service_path(service), class: "button primary-button" %>
    <%= button_to "Видалити", service_path(service), method: :delete, class: "button red-button" %>
  </div>
</div>

app/views/worker_accounts/_service_order.html.erb
<div class="service">
  <%= link_to service_order_path(service_order) do %>
    <h3> <%= service_order.service.title %> </h3>
    <p> Контакт: <%= service_order.contact_info %> </p>
    <p> Повне ім'я замовника: <%= service_order.user.full_name %> </p>
    <p> <%= service_order.description %> </p>
    <p> Статус: <%= service_order_status(service_order.status) %> </p>
  <% end %>
  <div class="mt-4 flex gap-3">
    <%= link_to "Детальніше", service_order_path(service_order), class: "button primary-button" %>
  </div>
</div>

app/views/worker_accounts/edit.html.erb
<div class="w-2/3 mx-auto block-wrapper">
  <h2> Редагувати інформацію робочого акаунту </h2>
  <div class="text-red-600">
    <%= render template: "layouts/flash", locals: { flash: flash[:error] } %>
  </div>
  <%= form_with model: @worker, method: :put, class: "flex flex-col" do |f| %>
    <div class="input-wrapper">
      <%= f.label :category, "Виберіть категорії, в яких ви будете надавати послуги" %>
      <%= f.collection_select :category_ids, Category.all, :id, :title, {  }, { multiple: true, class: "mb-3 js-multiple-select", required: true} %>
    </div>
    <div class="input-wrapper">
      <%= f.label :description, "Ваш короткий опис" %>
      <%= f.text_area :description, value: @worker.description, class: "min-h-[120px]", required: true %>
    </div>
    <div class="input-wrapper">
      <%= f.label :looking_for_work, "На даний момент відкриті до нових пропозицій" %>
      <%= f.check_box :looking_for_work, value: @worker.looking_for_work, class: "mr-auto"%>
    </div>
    <div class="flex gap-4 mt-5 justify-end">
      <%= link_to "< Назад ", request.referrer, class: "button secondary-button" %>
      <%= f.submit "Редагувати", class: "button primary-button" %>
    </div>
  <% end %>
</div>

app/views/worker_accounts/service_orders.html.erb
<%= render partial: "worker_accounts/personal_info" %>
<div class="mt-6 flex gap-6">
  <%= link_to "Ваші створені послуги", worker_accounts_path, class: "tab" %>
  <div class="tab active-tab"> Отримані замовлення </div>
</div>
<div class="service-wrapper mt-6">
  <% @service_orders.each do |service_order| %>
    <%= render partial: "worker_accounts/service_order", locals: { service_order: service_order } %>
  <% end %>
</div>
<% if @pagy.pages > 1 %>
  <%= render template: "layouts/pagination", locals: { pagy: @pagy } %>
<% end %>

app/views/worker_accounts/show.html.erb
<%= render partial: "worker_accounts/personal_info" %>
<div class="mt-6 flex gap-6">
  <div class="tab active-tab"> Ваші створені послуги </div>
  <%= link_to "Отримані замовлення", service_orders_worker_accounts_path, class: "tab" %>
</div>
<div class="service-wrapper mt-6">
  <% @services.each do |service| %>
    <%= render partial: "worker_accounts/service", locals: { service: service } %>
  <% end %>
</div>
<% if @pagy.pages > 1 %>
  <%= render template: "layouts/pagination", locals: { pagy: @pagy } %>
<% end %>