config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"
  resource :sessions, only: %i(destroy create new)
  resources :users
  resources :workers
  resource :worker_accounts, only: %i(show edit) do
    get :service_orders, on: :collection
  end
  resources :services do
    resources :service_orders, only: %i(new)
  end
  resources :service_orders, except: :new do
    get :cancellation_reason, on: :member
    get :rate, on: :member
  end
  resource :personal_informations, only: %i(show edit update)
  resources :notifications, only: %i(index destroy) do
    collection do
      delete :destroy_all
    end
  end
end

app/controllers/personal_informations_controller.rb
class PersonalInformationsController < ApplicationController
  before_action :require_authorization, :user

  def show
    @pagy, @service_orders = pagy(@user.service_orders.order(created_at: :desc))
  end

  def edit
  end

  def update
    if @user.update(user_params)
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:error] = @user.errors.full_messages
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def user
    @user ||= current_user
  end

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation, :full_name,
                                 :phone_number, :email, :date_of_birth)
  end
end

app/helpers/personal_informations_helper.rb
module PersonalInformationsHelper
end

app/views/personal_informations/_service_order.html.erb
<%= link_to service_order_path(service_order), class: "service" do %>
  <p class="text-xs"> Було створено <%= time_ago_in_words(service_order.created_at) %> </p>
  <h3> <%= service_order.service.title %> </h3>
  <p> <%= service_order.contact_info %> </p>
  <p> <%= service_order.description %> </p>
  <p> Поточний статус: <%= service_order_status(service_order.status) %> </p>
<% end %>

app/views/personal_informations/edit.html.erb
<div class="w-2/3 mx-auto block-wrapper">
  <h2> Редагувати особисту інформацію </h2>
  <%= render template: "layouts/flash", locals: { flash: flash[:error] } %>
  <%= form_with model: @user, url: personal_informations_path, method: :patch, class: "flex flex-col" do |f| %>
    <div class="input-wrapper">
      <%= f.label :email, "Електронна пошта *" %>
      <%= f.text_field :email, placeholder: "example@email.com", required: true %>
    </div>
    <div class="input-wrapper">
      <%= f.label :full_name, "Повне ім'я *" %>
      <%= f.text_field :full_name, placeholder: "Іван Шевченко", required: true %>
    </div>
    <div class="input-wrapper">
      <%= f.label :username, "Ім'я користувача *" %>
      <%= f.text_field :username, placeholder: "ivan_shevchenko", required: true %>
    </div>
    <div class="input-wrapper">
      <%= f.label :phone_number, "Телефон *" %>
      <%= f.text_field :phone_number, placeholder: "380991234141", required: true %>
    </div>
    <div class="input-wrapper">
      <%= f.label :date_of_birth, "Дата народження" %>
      <%= f.date_field :date_of_birth, as: :date %>
    </div>
    <div class="flex gap-4 mt-5 justify-end">
      <%= link_to "< Назад ", request.referrer, class: "button secondary-button" %>
      <%= f.submit "Підтвердити", class: "button primary-button" %>
    </div>
  <% end %>
</div>

app/views/personal_informations/show.html.erb
<div class="block-wrapper">
  <h2> Ваша персональна інформація </h2>
  <p> Повне ім'я: <%= @user.full_name %> </p>
  <p> Електронна пошта: <%= @user.email %> </p>
  <p> Номер телефону: <%= @user.phone_number %> </p>
  <p> Ваш псевдонім: <%= @user.username %> </p>
  <p> Дата народження: <%= @user.date_of_birth %> </p>
  <div class="flex gap-4 mt-5 justify-end">
    <%= link_to "Редагувати", edit_personal_informations_path, class: "button primary-button" %>
  </div>
</div>
<div class="block-wrapper mt-4">
  <h3> Ваші замовлення </h3>
  <div class="service-wrapper">
    <% @service_orders.each do |service_order| %>
      <%= render partial: "personal_informations/service_order", locals: { service_order: service_order }%>
    <% end %>
    <% if @service_orders.empty? %>
      <em> У вас ще немає замовлень </em>
    <% end %>
  </div>
  <% if @pagy.pages > 1 %>
    <%= render template: "layouts/pagination", locals: { pagy: @pagy } %>
  <% end %>
</div>