config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"
  resource :sessions, only: %i(destroy create new)
  resources :users
  resources :workers
  resource :worker_accounts, only: %i(show edit) do
    get :service_orders, on: :collection
  end
  resources :services do
    resources :service_orders, only: %i(new)
  end
  resources :service_orders, except: :new do
    get :cancellation_reason, on: :member
    get :rate, on: :member
  end
  resource :personal_informations, only: %i(show edit update)
  resources :notifications, only: %i(index destroy) do
    collection do
      delete :destroy_all
    end
  end
end

app/views/layouts/_nav_bar.html.erb
<nav class="bg-gray-900">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
    <%= link_to root_path, class: "flex items-center space-x-3" do %>
      <img src="https://flowbite.com/docs/images/logo.svg" class="h-8" alt="Flowbite Logo" />
      <span class="self-center text-2xl font-semibold whitespace-nowrap text-white">Рід</span>
    <% end %>
    <div class="w-auto" id="navbar-default">
      <ul class="flex items-center flex-row bg-gray-900">
        <li>
          <%= link_to "Головна", root_path, class: "block py-2 px-3 text-white text-xl hover:text-blue-400" %>
        </li>
        <li>
          <%= link_to "Виконавці", workers_path, class: "block py-2 px-3 text-white text-xl hover:text-blue-400" %>
        </li>
        <% if current_user %>
          <% if current_user.worker.present? %>
            <%= link_to "Робочий акаунт", worker_accounts_path, class: "block py-2 px-3 text-white text-xl hover:text-blue-400" %>
          <% else %>
            <%= link_to "Зареєструвати робочий акаунт", new_worker_path, class: "button primary-button" %>
          <% end %>
          <%= link_to notifications_path do %>
            <%= inline_svg "bell_solid.svg", class: notification_bell_classes(current_user) %>
          <% end %>
          <%= link_to current_user.full_name, personal_informations_path, class: "hover:text-blue-400 text-white py-2 px-3 leading-7" %>
          <%= button_to "Вийти", sessions_path, method: :delete, class: "block py-2 px-3 text-red-400 text-xl hover:text-red-500"  %>
        <% else %>
          <%= link_to "Реєстрація", new_user_path, class: "button primary-button" %>
          <%= link_to "Авторизація", new_sessions_path, class: "button primary-button ml-2" %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Рід</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render partial: "layouts/nav_bar" %>
    <div class="max-w-screen-xl mx-auto mt-4">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/flash.html.erb
<% if flash %>
  <div class="flex flex-col">
    <% flash.each do |msg| %>
      <div><%= msg %></div>
    <% end %>
    <% flash.clear %>
  </div>
<% end %>

app/views/layouts/pagination.html.erb
<div class="text-center mt-8">
  <%= render template: "layouts/pagy", locals: { pagy: @pagy } %>
</div>

app/views/layouts/pagy.html.erb
<% link = pagy_link_proc(pagy) %>

<div class="pagy_nav pagination" aria-label="pager" role="navigation">
  <% if pagy.prev %>
    <span class="page prev"><%= link.call(pagy.prev, "<", 'aria-label="previous"').html_safe %></span>
  <% else %>
    <span class="page prev disabled"> < </span>
  <% end %>
  <% pagy.series.each do |item| %>
    <% if item.is_a?(Integer) %>
      <span class="page">
        <%= link.call(item).html_safe %>
      </span>
    <% elsif item.is_a?(String) %>
      <span class="page current"><%= item %></span>
    <% elsif item == :gap %>
      <span class="page gap"><%= pagy_t('pagy.nav.gap') %></span>
    <% end %>
  <% end %>
  <% if pagy.next %>
    <span class="page next"><%= link.call(pagy.next, ">", 'aria-label="next"').html_safe %></span>
  <% else %>
    <span class="page next disabled"> > </span>
  <% end %>
</div>